substitutions:
  dev_name: smartlife_c4dd57167349

esphome:
  name: ${dev_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret passwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${dev_name}
    password: "12345678"
    
captive_portal:
    
# Enable logging
logger:

# Enable Home Assistant API
api:
    password: "12345678"
ota:
    password: "12345678"

status_led:
  pin: 1

switch:
  - platform: restart
    name: ${dev_name}_restart

output:
  - platform: gpio
    pin: 12
    id: ${dev_name}_relay
    
light:
  - platform: binary
    name: ${dev_name}_light
    id: ${dev_name}_light
    output: ${dev_name}_relay
    restore_mode: RESTORE_DEFAULT_OFF
    
binary_sensor:
  - platform: gpio
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: True
    id: ${dev_name}_button
    on_press:
      light.toggle: ${dev_name}_light
        
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${dev_name}_ip
      icon: "mdi:lan"
    ssid:
      name: ${dev_name}_ssid
      icon: "mdi:wifi"
    mac_address:
      name: ${dev_name}_mac
      icon: "mdi:lan"